version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: milanweek_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: milanweek
      POSTGRES_USER: milanweek_user
      POSTGRES_PASSWORD: milanweek_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"

volumes:
  postgres_data: